### PR TITLE
Update triton to 3.1.0 and triton-viz to 1.1.1

### PR DESCRIPTION
**Pull request by Jokeren**

### CODE REVIEW

**Comment by Jokeren** [comment]
image

**Comment by Jokeren** [comment]
Hi @srush , can you please take a look? Thanks

**Comment by Jokeren** [comment]
I'm not quite sure why `pycairo` has to be installed manually. It's just a workaround. Happy to change if you have any suggestion

**Comment by mark14wu** [comment]
This fix solves #24 #22 .

**Pull request merged**
